#!/usr/bin/env node
// build-data.mjs
// Scans {dir}/src for .vue / .js / .css / .json sources and (re)generates
// {dir}/preview-data.js — the source map consumed by index.gts.html to
// compile SFCs in the browser via vue3-sfc-loader.
//
// Also exported as a module function so build.mjs auto-runs it (standalone
// use is rarely needed).
//
// Usage:
//   node build-data.mjs --dir "{artifact-folder}/{slug}"
//
// Output (agent-parseable):
//   RESULT: OK
//   FILES: <count of embedded sources>
//   DATA_PATH: <absolute path to preview-data.js>
//   RESULT: FAIL | <reason>

import { existsSync, readFileSync, writeFileSync, readdirSync, statSync } from 'fs';
import { join, resolve, dirname, extname } from 'path';
import { fileURLToPath } from 'url';

const __dirname = dirname(fileURLToPath(import.meta.url));

const TEXT_EXT = new Set(['.vue', '.js', '.mjs', '.css', '.json']);

export function collectSources(srcDir) {
  const files = [];
  (function walk(dir) {
    for (const entry of readdirSync(dir, { withFileTypes: true })) {
      const full = join(dir, entry.name);
      if (entry.isDirectory()) {
        if (entry.name === 'node_modules' || entry.name.startsWith('.')) continue;
        walk(full);
      } else if (TEXT_EXT.has(extname(entry.name))) {
        files.push(full);
      }
    }
  })(srcDir);
  const map = {};
  for (const f of files) {
    // key: "/src/..." posix path — matches the paths vue3-sfc-loader resolves
    // (entry '/src/App.vue', relative imports resolve under '/src/...')
    const rel = f.slice(srcDir.length).split('\\').join('/').replace(/^\/+/, '');
    map['/src/' + rel] = readFileSync(f, 'utf8');
  }
  return map;
}

export function refresh(dir) {
  const root = resolve(dir);
  const srcDir = join(root, 'src');
  if (!existsSync(srcDir) || !statSync(srcDir).isDirectory()) {
    return { ok: false, reason: `src folder not found: ${srcDir}` };
  }
  if (!existsSync(join(root, 'index.gts.html'))) {
    return { ok: false, reason: `index.gts.html not found: ${join(root, 'index.gts.html')}` };
  }
  const map = collectSources(srcDir);
  if (!map['/src/App.vue']) {
    return { ok: false, reason: 'src/App.vue not found (preview entry)' };
  }
  const stamp = new Date().toISOString();
  const dataPath = join(root, 'preview-data.js');
  const body =
    `// AUTO-GENERATED by build-data.mjs (${stamp}) — do not edit\n` +
    `// key = path from src root; consumed by index.gts.html + vue3-sfc-loader\n` +
    `window.__GTS_SRC__ = ${JSON.stringify(map, null, 0)};\n` +
    `window.__GTS_REFRESHED_AT = ${JSON.stringify(stamp)};\n`;
  writeFileSync(dataPath, body, 'utf8');
  return { ok: true, count: Object.keys(map).length, dataPath };
}

// ---------- CLI ----------
if (process.argv[1] && resolve(process.argv[1]) === resolve(fileURLToPath(import.meta.url))) {
  const args = process.argv.slice(2);
  const idx = args.findIndex((a) => a === '--dir' || a === '-d');
  const dir = idx !== -1 ? args[idx + 1] : undefined;
  if (!dir) {
    console.log('RESULT: FAIL | Usage: node build-data.mjs --dir "<folder with src/ and index.gts.html>"');
    process.exit(1);
  }
  const result = refresh(dir);
  if (!result.ok) {
    console.log(`RESULT: FAIL | ${result.reason}`);
    process.exit(1);
  }
  console.log('RESULT: OK');
  console.log(`FILES: ${result.count}`);
  console.log(`DATA_PATH: ${result.dataPath}`);
}
